# Task6: Attendance Tracker
days_of_the_week = ("Monday", "Tuesday", "Wednesday", "Thursday", "F")
print(days_of_the_week)
months_of_the_year = ("January", "February", "March", "April")
print(months_of_the_year)
Student_name = input("student'name")
Gender = input("Enter Gender")
Course_Track = input("Course Track")
Current_month_number = int(input("current month number"))
Current_day_number = int(input("Enter current day number"))
print(Student_name)
print(Gender)
print(Course_Track)
print(Current_month_number)
print(Current_day_number)